module.exports = {
  USER_INFO_CONST: {
    MIN_NAME_LENGTH : 1,
    MAX_NAME_LENGTH : 30,
    MIN_DISPLAYNAME_LENGTH : 3,
    MAX_DISPLAYNAME_LENGTH : 20,
    MIN_PASSWORD_LENGTH : 10,
    MAX_PASSWORD_LENGTH : 20,
    MIN_AGE : 14,
    MAX_AGE : 100
  },
  EVENT_INFO_CONST:{
    MIN_NAME_LENGTH: 5,
    MAX_NAME_LENGTH: 100,
    MIN_DESCRIPTION_LENGTH: 20,
    MAX_DESCRIPTION_LENGTH: 200
  }
}
