module.exports = {
  USER_INFO_CONST: {
    MIN_NAME_LENGTH : 1,
    MAX_NAME_LENGTH : 30,
    MIN_DISPLAYNAME_LENGTH : 1,
    MAX_DISPLAYNAME_LENGTH : 20,
    MIN_AGE : 14,
    MAX_AGE : 100
  },
  EVENT_INFO_CONST:{}
}
